version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "30001:8080"
    links:
    - mongo
    - redis
  mongo:
    image: mongo
    ports:
    - "27017"
  redis:
    image: redis
    ports:
    - "6379"
